// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConnection() {
  return window['go']['desktop']['App']['CloseConnection']();
}

export function CreateHost(arg1) {
  return window['go']['desktop']['App']['CreateHost'](arg1);
}
