// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ConnectToClient(arg1:string):Promise<string>;

export function ConnectToHost(arg1:string):Promise<string>;

export function CreateHost():Promise<string>;

export function DomReady(arg1:context.Context):Promise<void>;
