// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentOS() {
  return window['go']['desktop']['App']['GetCurrentOS']();
}

export function OpenViGEmWizard() {
  return window['go']['desktop']['App']['OpenViGEmWizard']();
}

export function TryClosePeerConnection() {
  return window['go']['desktop']['App']['TryClosePeerConnection']();
}

export function TryCreateHost(arg1, arg2) {
  return window['go']['desktop']['App']['TryCreateHost'](arg1, arg2);
}
