// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToClient(arg1) {
  return window['go']['desktop']['App']['ConnectToClient'](arg1);
}

export function ConnectToHost(arg1) {
  return window['go']['desktop']['App']['ConnectToHost'](arg1);
}

export function CreateHost() {
  return window['go']['desktop']['App']['CreateHost']();
}

export function DomReady(arg1) {
  return window['go']['desktop']['App']['DomReady'](arg1);
}
