// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugins} from '../models';
import {webrtc} from '../models';

export function GetCurrentOS():Promise<string>;

export function GetNATSPort():Promise<number>;

export function GetPlugin(arg1:string):Promise<plugins.Plugin>;

export function GetPlugins():Promise<Array<plugins.Plugin>>;

export function InitClientPlugin(arg1:string):Promise<void>;

export function ModifyPluginArgs(arg1:string,arg2:Array<plugins.Plugin_arg>,arg3:string):Promise<void>;

export function OpenViGEmWizard():Promise<string>;

export function ReloadPlugins():Promise<void>;

export function TooglePlugin(arg1:string):Promise<void>;

export function TryClosePeerConnection():Promise<boolean>;

export function TryCreateHost(arg1:Array<webrtc.ICEServer>,arg2:string):Promise<string>;
