// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConnection():Promise<boolean>;

export function CreateHost(arg1:string):Promise<string>;
